config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "cooks#index"
  resources :users
  resources :cooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cook, dependent: :destroy
  attachment :profile_image
   validates :name, presence: true
   validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cook_params)
    @cook.user_id = current_user.id
    @cook.save
    redirect_to cooks_path
  end

  def index
    @cooks = Cook.all
  end

  def edit
    @cook = Cook.find(params[:id])
  end

  def show
    @cook = Cook.find(params[:id])
  end
  
  def update
    @cook = Cook.find(params[:id])
    @cook.update(cook_params)
    redirect_to cook_path(@cook)
  end

  def destroy
    @cook = Cook.find(params[:id])
    @cook.destroy
    redirect_to cooks_path
  end

  private

  def cook_params
    params.require(:cook).permit(:cook_name, :caption, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_cooks = @user.cook
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cooks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Cook Edit</h1>
      <%= form_with model:@cook, local:true do |f| %>
        <h4>写真</h4>
        <%= f.attachment_field :image %>
        <h4>料理名</h4>
        <%= f.text_field :cook_name %>
        <h4>作り方（メモ）</h4>
        <%= f.text_area :caption %><br >
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
      <% end %>
      <%= link_to "戻る", cooks_path %>
    </div>
  </div>
</div>

app/views/cooks/index.html.erb
<div class="contanier">
  <div class="row mx-auto p-0 d-flex align-content-start flex-wrap">
    <% @cooks.each do |cook| %>
      <div class="col-2">
        <%= link_to cook_path(cook) do %>
        <%= attachment_image_tag cook, :image, :fill, 400, 400, format: 'jpeg', fallback: "no_image.png",size:'250x250' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<!--m-->

app/views/cooks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>料理の投稿</h1>
      <%= form_with model:@cook, local:true do |f| %>
        <h4>料理の写真</h4>
        <%= f.attachment_field :image %>
        <h4>料理名</h4>
        <%= f.text_field :cook_name %>
        <h4>作り方（メモ）</h4>
        <%= f.text_area :caption %><br >
        <%= f.submit '投稿', class: "btn btn-primary" %>
      <% end %>
      <%= link_to "戻る", cooks_path %>
    </div>
  </div>
</div>

app/views/cooks/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
      <%= current_user.name %>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png", size:'100x100' %>


      <h1><%= @cook.cook_name%>の詳細</h1>

      <%= attachment_image_tag @cook, :image, :fill, 300, 300 %>
      <p>料理の名前<%= @cook.cook_name %></p>
      <p>作り方（メモ）<%= @cook.caption%></p>

      <% if @cook.user == current_user %>
        <%= link_to "削除", cook_path(@cook), method: :delete %>
        <%= link_to "編集", edit_cook_path(@cook) %>
      <% end %>
        <%= link_to "戻る", cooks_path %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeCook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header p-3 mb-2 bg-secondary text-white">
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">アイコン</div>
          <% if user_signed_in? %>
            <li class="p-2 bd-highlight">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
            </li>
          <% else %>
            <li class="p-2 bd-highlight">
              <%= link_to "新規登録", new_user_registration_path, class: "text-white" %>
            </li>
            <li class="p-2 bd-highlight">
              <%= link_to "ログイン", new_user_session_path, class: "text-white" %>
            </li>
          <% end %>
            <p class="p-2 bd-highlight">
              <%= link_to "ユーザー一覧", users_path, class: "text-white" %>
            </p>
            <p class="p-2 bd-highlight">
              <%= link_to "料理一覧", cooks_path, class: "text-white" %>
            </p>
            <p><%= link_to "レシピの投稿", new_cook_path, class: "btn btn-primary" %></p>
        </div>
      </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
      <div class="p-3 mb-2 bg-secondary text-white text-center">
        Home_cook
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>プロフィールの編集</h1>
<%= form_with model:@user, local:true do |f| %>
  <h4>Name</h4>
  <%= f.text_field :name %>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png"%>
  <h4>ProfileImage</h4>
  <%= f.attachment_field :profile_image %>
  <%= f.submit "変更を保存" %>
<% end %>

<%= link_to "戻る", users_path %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">

      <p><%= current_user.name %></p>
      <p><%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png", size:'100x100' %></p>
      <p><%= link_to "プロフィールの編集", edit_user_path(current_user) %></p>

      <% @users.each do |user| %>
        <p><%= link_to user.name, user_path(user) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= current_user.name %>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png", size:'100x100' %>

      <h1 class="py-4"><%= @user.name %>の料理</h1>

      <% @user_cooks.each do |user_cook| %>
        <%=link_to cook_path(user_cook) do %>
        <%= attachment_image_tag user_cook, :image, :fill, 100, 100 %>
        <% end %>
      <% end %>
      <p class="py-4"><%= link_to "戻る", users_path %></p>
    </div>
  </div>
</div>